import { v4 as uuidv4 } from 'uuid';
import type { InvoiceDocument } from '../types/invoice';
import { recalculate } from '../utils/recalculate';
import { createLineItem, insertOne } from './invoiceDB';

function makeInvoice(overrides: Omit<InvoiceDocument, '_id' | 'createdAt' | 'updatedAt'>) {
  const calc = recalculate({ ...overrides, _id: '', createdAt: '', updatedAt: '' } as InvoiceDocument);
  const { _id, createdAt, updatedAt, ...doc } = calc;
  insertOne(doc);
}

export function seedTestData() {
  // ── Invoice 1: Web Platform (TN → KA, IGST, saved) ────────────────────────
  makeInvoice({
    invoiceNumber: 'INV2026-0001',
    status: 'saved',
    invoiceDate: '2026-04-05',
    dueDate: '2026-05-05',
    currency: 'INR',
    poNumber: 'PO-2026-0042',
    projectName: 'E-Commerce Web Platform',
    eWayBillNumber: '', transportName: '', vehicleNumber: '',
    companyName: 'TechSoft Solutions Pvt. Ltd.',
    companyAddress: '42, Rajiv Gandhi Salai, Sholinganallur',
    companyEmail: 'dhanushwar771@gmail.com',
    companyPhone: '+91 98400 12345',
    companyGst: '33AABCT1234F1Z5',
    companyLogo: null, companySeal: null, signature: null,
    companyLocation: { country: 'IN', state: 'TN', city: 'Chennai', pincode: '600119' },
    clientName: 'Nexus Retail India Pvt. Ltd.',
    clientAddress: '15, Brigade Road, Shivajinagar',
    clientEmail: 'dhanushwarjp@gmail.com',
    clientPhone: '+91 80 4567 8901',
    clientGst: '29AACCN5678G1ZK',
    clientLocation: { country: 'IN', state: 'KA', city: 'Bengaluru', pincode: '560025' },
    deliverySameAsBilling: false, siteName: '', deliveryAddress: '',
    deliveryLocation: { country: '', state: '', city: '', pincode: '' },
    lineItems: [
      { description: 'Website Design & Development', hsnCode: '998314', uom: 'Job', quantity: 1, unitRate: 85000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'UI/UX Wireframing', hsnCode: '998314', uom: 'Job', quantity: 1, unitRate: 25000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'React Frontend Development', hsnCode: '998314', uom: 'Hrs', quantity: 120, unitRate: 800, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Node.js Backend API', hsnCode: '998314', uom: 'Hrs', quantity: 80, unitRate: 900, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Database Design (PostgreSQL)', hsnCode: '998314', uom: 'Job', quantity: 1, unitRate: 18000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Cloud Hosting Setup (AWS)', hsnCode: '998316', uom: 'Months', quantity: 3, unitRate: 4500, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'SSL Certificate (1 Year)', hsnCode: '998316', uom: 'Pcs', quantity: 1, unitRate: 3500, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Domain Registration', hsnCode: '998316', uom: 'Year', quantity: 2, unitRate: 1200, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'SEO Optimization Package', hsnCode: '998361', uom: 'Months', quantity: 3, unitRate: 12000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Content Writing (Blog Posts)', hsnCode: '998390', uom: 'Pcs', quantity: 10, unitRate: 1500, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Mobile Responsive Testing', hsnCode: '998314', uom: 'Hrs', quantity: 20, unitRate: 600, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Payment Gateway Integration', hsnCode: '998314', uom: 'Job', quantity: 1, unitRate: 15000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Admin Dashboard Development', hsnCode: '998314', uom: 'Hrs', quantity: 40, unitRate: 850, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Project Management & Coordination', hsnCode: '998311', uom: 'Months', quantity: 4, unitRate: 8000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Post-Launch Support & Maintenance', hsnCode: '998314', uom: 'Months', quantity: 3, unitRate: 10000, tax: 'GST 18%' as const, taxRate: 18 },
    ].map((item) => createLineItem({ ...item, _id: uuidv4() })),
    discountType: 'percentage', discountValue: 5, discountAmount: 0, discountedSubtotal: 0,
    additionalCharges: [{ _id: uuidv4(), type: 'Freight Charges', label: 'Freight Charges', amount: 2500 }],
    taxRate: 18, subtotal: 0, taxAmount: 0,
    totalCGST: 0, totalSGST: 0, totalIGST: 0,
    isIntraState: false, isExport: false, additionalChargesTotal: 0, roundOff: 0, grandTotal: 0,
    notes: 'Payment due within 30 days.\nBank transfer preferred.',
    termsAndConditions: '1. All prices in INR.\n2. GST applicable.\n3. Work starts after advance payment.\n4. Source code delivered on full payment.',
    paymentMethod: 'Bank Transfer',
    attachments: [],
  });

  // ── Invoice 2: Interior Design (MH → MH, CGST+SGST intra-state, saved) ────
  makeInvoice({
    invoiceNumber: 'INV2026-0002',
    status: 'saved',
    invoiceDate: '2026-04-12',
    dueDate: '2026-05-12',
    currency: 'INR',
    poNumber: 'PO-MH-0089',
    projectName: 'Corporate Office Interior',
    eWayBillNumber: 'EWB1234567890', transportName: 'Blue Dart', vehicleNumber: 'MH04-AB-1234',
    companyName: 'DesignCraft Interiors LLP',
    companyAddress: '7th Floor, Bandra Kurla Complex',
    companyEmail: 'invoices@designcraft.co.in',
    companyPhone: '+91 22 6789 0123',
    companyGst: '27AADFD4567H1Z3',
    companyLogo: null, companySeal: null, signature: null,
    companyLocation: { country: 'IN', state: 'MH', city: 'Mumbai', pincode: '400051' },
    clientName: 'Prestige Realty Ltd.',
    clientAddress: '3rd Floor, Nariman Point',
    clientEmail: 'finance@prestigerealty.com',
    clientPhone: '+91 22 2345 6789',
    clientGst: '27AAECP9012J1ZL',
    clientLocation: { country: 'IN', state: 'MH', city: 'Mumbai', pincode: '400021' },
    deliverySameAsBilling: false, siteName: 'Andheri West Office', deliveryAddress: 'Plot 12, MIDC, Andheri West',
    deliveryLocation: { country: 'IN', state: 'MH', city: 'Mumbai', pincode: '400053' },
    lineItems: [
      { description: 'Space Planning & Concept Design', hsnCode: '998311', uom: 'Job', quantity: 1, unitRate: 45000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'False Ceiling (Gypsum Board)', hsnCode: '940360', uom: 'Sqft', quantity: 2800, unitRate: 85, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Modular Workstations (48 Units)', hsnCode: '940360', uom: 'Nos', quantity: 48, unitRate: 18500, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Conference Table (12 Seater)', hsnCode: '940360', uom: 'Nos', quantity: 2, unitRate: 65000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Ergonomic Office Chairs', hsnCode: '940130', uom: 'Nos', quantity: 60, unitRate: 8500, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Vinyl Flooring Installation', hsnCode: '390410', uom: 'Sqft', quantity: 3500, unitRate: 65, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Electrical Works & Cabling', hsnCode: '854442', uom: 'Job', quantity: 1, unitRate: 120000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Interior Painting (2 Coats)', hsnCode: '320910', uom: 'Sqft', quantity: 8000, unitRate: 18, tax: 'GST 18%' as const, taxRate: 18 },
    ].map((item) => createLineItem({ ...item, _id: uuidv4() })),
    discountType: 'flat', discountValue: 25000, discountAmount: 0, discountedSubtotal: 0,
    additionalCharges: [
      { _id: uuidv4(), type: 'Freight Charges', label: 'Transportation & Logistics', amount: 18000 },
      { _id: uuidv4(), type: 'Installation Charges', label: 'Installation Charges', amount: 35000 },
    ],
    taxRate: 18, subtotal: 0, taxAmount: 0,
    totalCGST: 0, totalSGST: 0, totalIGST: 0,
    isIntraState: true, isExport: false, additionalChargesTotal: 0, roundOff: 0, grandTotal: 0,
    notes: 'Advance of 40% required before work commencement.\nBalance payable on project handover.',
    termsAndConditions: '1. Prices include material and labour.\n2. Client to ensure site access during working hours.\n3. Warranty: 1 year on workmanship.',
    paymentMethod: 'Cheque',
    attachments: [],
  });

  // ── Invoice 3: Solar Equipment export (GJ → Export, zero GST, saved) ──────
  makeInvoice({
    invoiceNumber: 'INV2026-0003',
    status: 'saved',
    invoiceDate: '2026-04-20',
    dueDate: '2026-05-20',
    currency: 'USD',
    poNumber: 'INTL-PO-7731',
    projectName: 'Solar Panel Export — Q1',
    eWayBillNumber: '', transportName: 'Maersk Line', vehicleNumber: 'MRSK-9923',
    companyName: 'SunPower Exports Pvt. Ltd.',
    companyAddress: 'Plot 18, GIDC Industrial Estate, Vatva',
    companyEmail: 'exports@sunpowerindia.com',
    companyPhone: '+91 79 2657 3344',
    companyGst: '24AAHFS3456K1ZQ',
    companyLogo: null, companySeal: null, signature: null,
    companyLocation: { country: 'IN', state: 'GJ', city: 'Ahmedabad', pincode: '382445' },
    clientName: 'GreenGrid Energy LLC',
    clientAddress: '500 Technology Drive, Austin',
    clientEmail: 'procurement@greengrid.us',
    clientPhone: '+1 512 800 4422',
    clientGst: '',
    clientLocation: { country: 'US', state: '', city: 'Austin, TX', pincode: '78701' },
    deliverySameAsBilling: true, siteName: '', deliveryAddress: '',
    deliveryLocation: { country: '', state: '', city: '', pincode: '' },
    lineItems: [
      { description: 'Monocrystalline Solar Panel 400W', hsnCode: '854140', uom: 'Pcs', quantity: 500, unitRate: 95, tax: 'None' as const, taxRate: 0 },
      { description: 'Polycrystalline Solar Panel 330W', hsnCode: '854140', uom: 'Pcs', quantity: 300, unitRate: 75, tax: 'None' as const, taxRate: 0 },
      { description: 'Solar Inverter 5kW Grid-Tie', hsnCode: '850440', uom: 'Nos', quantity: 50, unitRate: 420, tax: 'None' as const, taxRate: 0 },
      { description: 'MPPT Charge Controller 60A', hsnCode: '850440', uom: 'Nos', quantity: 100, unitRate: 180, tax: 'None' as const, taxRate: 0 },
      { description: 'Mounting Structure (Rooftop)', hsnCode: '730820', uom: 'Sets', quantity: 80, unitRate: 210, tax: 'None' as const, taxRate: 0 },
      { description: 'DC Cable 4mm² (per metre)', hsnCode: '854442', uom: 'Mtrs', quantity: 5000, unitRate: 1.20, tax: 'None' as const, taxRate: 0 },
    ].map((item) => createLineItem({ ...item, _id: uuidv4() })),
    discountType: 'percentage', discountValue: 3, discountAmount: 0, discountedSubtotal: 0,
    additionalCharges: [
      { _id: uuidv4(), type: 'Freight Charges', label: 'Sea Freight (CIF Austin)', amount: 4800 },
      { _id: uuidv4(), type: 'Packing Charges', label: 'Export Packing & Labelling', amount: 1200 },
    ],
    taxRate: 0, subtotal: 0, taxAmount: 0,
    totalCGST: 0, totalSGST: 0, totalIGST: 0,
    isIntraState: false, isExport: true, additionalChargesTotal: 0, roundOff: 0, grandTotal: 0,
    notes: 'Payment by LC (Letter of Credit) within 45 days.\nShipment ETA: 15 working days from PO confirmation.',
    termsAndConditions: '1. Prices are CIF Austin, TX.\n2. Insurance covered by seller up to port of destination.\n3. All disputes subject to ICC Arbitration, Geneva.',
    paymentMethod: 'Bank Transfer',
    attachments: [],
  });

  // ── Invoice 4: Pharma Distribution (DL → DL, intra-state, saved) ──────────
  makeInvoice({
    invoiceNumber: 'INV2026-0004',
    status: 'saved',
    invoiceDate: '2026-05-02',
    dueDate: '2026-05-17',
    currency: 'INR',
    poNumber: 'PO-DL-5512',
    projectName: '',
    eWayBillNumber: '', transportName: '', vehicleNumber: '',
    companyName: 'MedSupply Distributors Pvt. Ltd.',
    companyAddress: '22, Patparganj Industrial Area',
    companyEmail: 'billing@medsupply.in',
    companyPhone: '+91 11 4321 9876',
    companyGst: '07AABCM7890D1ZE',
    companyLogo: null, companySeal: null, signature: null,
    companyLocation: { country: 'IN', state: 'DL', city: 'New Delhi', pincode: '110092' },
    clientName: 'Apollo Pharmacy — Rohini',
    clientAddress: 'Shop 4, Sector 9, Rohini',
    clientEmail: 'purchase.rohini@apollopharmacy.in',
    clientPhone: '+91 11 2778 4400',
    clientGst: '07AABCA1234P1ZR',
    clientLocation: { country: 'IN', state: 'DL', city: 'New Delhi', pincode: '110085' },
    deliverySameAsBilling: true, siteName: '', deliveryAddress: '',
    deliveryLocation: { country: '', state: '', city: '', pincode: '' },
    lineItems: [
      { description: 'Paracetamol 500mg Strip (10 Tabs)', hsnCode: '300490', uom: 'Strips', quantity: 2000, unitRate: 18, tax: 'GST 12%' as const, taxRate: 12 },
      { description: 'Amoxicillin 500mg Capsules (10)', hsnCode: '300490', uom: 'Strips', quantity: 500, unitRate: 45, tax: 'GST 12%' as const, taxRate: 12 },
      { description: 'ORS Sachets (Orange, Box of 20)', hsnCode: '300490', uom: 'Boxes', quantity: 300, unitRate: 120, tax: 'GST 12%' as const, taxRate: 12 },
      { description: 'Cetirizine 10mg Tablet (15 Tabs)', hsnCode: '300490', uom: 'Strips', quantity: 800, unitRate: 28, tax: 'GST 12%' as const, taxRate: 12 },
      { description: 'Betadine Antiseptic Solution 100ml', hsnCode: '300590', uom: 'Btls', quantity: 200, unitRate: 85, tax: 'GST 12%' as const, taxRate: 12 },
      { description: 'Surgical Gloves (Box of 100)', hsnCode: '401511', uom: 'Boxes', quantity: 150, unitRate: 320, tax: 'GST 12%' as const, taxRate: 12 },
      { description: 'N95 Masks (Box of 20)', hsnCode: '630790', uom: 'Boxes', quantity: 100, unitRate: 450, tax: 'GST 5%' as const, taxRate: 5 },
    ].map((item) => createLineItem({ ...item, _id: uuidv4() })),
    discountType: 'flat', discountValue: 5000, discountAmount: 0, discountedSubtotal: 0,
    additionalCharges: [],
    taxRate: 12, subtotal: 0, taxAmount: 0,
    totalCGST: 0, totalSGST: 0, totalIGST: 0,
    isIntraState: true, isExport: false, additionalChargesTotal: 0, roundOff: 0, grandTotal: 0,
    notes: 'Cold-chain items must be stored at 2–8 °C upon receipt.',
    termsAndConditions: '1. Returns accepted within 7 days for damaged goods only.\n2. Batch numbers verified at time of dispatch.',
    paymentMethod: 'UPI',
    attachments: [],
  });

  // ── Invoice 5: IT Consulting draft (HR → UP, IGST, draft) ─────────────────
  makeInvoice({
    invoiceNumber: 'INV2026-0005',
    status: 'draft',
    invoiceDate: '2026-05-15',
    dueDate: '2026-06-14',
    currency: 'INR',
    poNumber: '',
    projectName: 'ERP Implementation — Phase 2',
    eWayBillNumber: '', transportName: '', vehicleNumber: '',
    companyName: 'Axiom Consulting Services',
    companyAddress: '8th Floor, Cyber City Tower B',
    companyEmail: 'accounts@axiomconsult.in',
    companyPhone: '+91 124 456 7890',
    companyGst: '06AABCA5678B1ZF',
    companyLogo: null, companySeal: null, signature: null,
    companyLocation: { country: 'IN', state: 'HR', city: 'Gurugram', pincode: '122002' },
    clientName: 'Bharat Agro Industries Ltd.',
    clientAddress: 'Industrial Estate, Kanpur Road',
    clientEmail: 'cfo@bharatagro.co.in',
    clientPhone: '+91 512 234 5678',
    clientGst: '09AABCB2345C1ZP',
    clientLocation: { country: 'IN', state: 'UP', city: 'Lucknow', pincode: '226012' },
    deliverySameAsBilling: false, siteName: '', deliveryAddress: '',
    deliveryLocation: { country: '', state: '', city: '', pincode: '' },
    lineItems: [
      { description: 'ERP Requirement Analysis', hsnCode: '998314', uom: 'Job', quantity: 1, unitRate: 60000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'SAP S/4HANA Configuration', hsnCode: '998314', uom: 'Hrs', quantity: 200, unitRate: 2500, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Data Migration & Cleansing', hsnCode: '998314', uom: 'Job', quantity: 1, unitRate: 75000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'User Training (5 Batches)', hsnCode: '999293', uom: 'Batches', quantity: 5, unitRate: 15000, tax: 'GST 18%' as const, taxRate: 18 },
      { description: 'Go-Live Support (4 Weeks)', hsnCode: '998314', uom: 'Weeks', quantity: 4, unitRate: 40000, tax: 'GST 18%' as const, taxRate: 18 },
    ].map((item) => createLineItem({ ...item, _id: uuidv4() })),
    discountType: 'percentage', discountValue: 0, discountAmount: 0, discountedSubtotal: 0,
    additionalCharges: [
      { _id: uuidv4(), type: 'Other', label: 'Travel & Accommodation', amount: 22000 },
    ],
    taxRate: 18, subtotal: 0, taxAmount: 0,
    totalCGST: 0, totalSGST: 0, totalIGST: 0,
    isIntraState: false, isExport: false, additionalChargesTotal: 0, roundOff: 0, grandTotal: 0,
    notes: 'Draft invoice — pending client PO confirmation.',
    termsAndConditions: '1. Billing in monthly milestones.\n2. Travel expenses billed at actuals with receipts.',
    paymentMethod: 'Bank Transfer',
    attachments: [],
  });

  console.log('✅ 5 test invoices seeded! Refresh the page.');
}
